### ISSUE TITLE
Gift cards does not work

### ISSUE THREAD

**Issue by jonas-jaderberg** [umbraco/Umbraco.Commerce.PaymentProviders.Klarna#3]
When you use a gift card on the order, that is not reflected/transfered to Klarna. In Klarna form you see the total amount without the Gift Card.

**Comment by mattbrailsford** [comment]
Hmm, the problem as I see it is that your OrderTaxAmount is potentially kind of off.

We see Gift Cards as effectively a form of pseudo payment method and so these shouldn't really have a tax amount to them, but there deduction is applied on the orders total price inc VAT so they effectively reduce the tax amount too when they are applied, but by not updating the OrderTaxAmount you could end up in a position where if the gift card is for almost the full order amount, the math might end up wrong because the OrderTaxAmount would be reducing.

**Comment by mattbrailsford** [comment]
Here's an example just using fake amounts

Say we have an order with

Order Total Price inc Tax = 100
Order Tax Amount = 20

Now lets say you have a Gift Card amount of 90 and so your updated code would be saying this

Order Total Price = 10
Order Tax Amount = 20

So I would assume here that Klarna would error because the Tax is now greater than the order total price and so the math doesn't add up.

When deducting a gift card, it would need to some how also deduct the tax amount. Unfortunately this isn't just a case though of taking the order tax rate and working it out backwards as it's possible to have order lines with differing tax rates, so the orders final tax amount could be made up of multiple different tax rates.

The ONLY way I could think of effectively reducing things evenly is to work out what percentage the tax amount is of the total order price, and use that percentage to reduce the order tax amount too if you see what I mean.

**Comment by jonas-jaderberg** [comment]
I think I understand.
I tested an even more extream case where the gift card was greater than the order value. The order value was 0 and the Tax 812,50 SEK.
Klarna did not reject the order. I payed 0.
The Klarna logs confirms this

{
  "merchant_urls": {},
  "merchant_reference1": "ORDER-01471-55441-BP8K4",
  "purchase_country": "SE",
  "purchase_currency": "SEK",
  "locale": "sv-SE",
  "order_lines": [
    {
      "reference": "0921ID10010",
      "name": "XXX 1",
      "tax_rate": 2500,
      "unit_price": 356250,
      "quantity": 1,
      "total_tax_amount": 71250,
      "total_amount": 356250
    },
    {
      "reference": "fraktp",
      "name": "Standardfrakt Privat Fee",
      "type": "shipping_fee",
      "tax_rate": 2500,
      "unit_price": 50000,
      "quantity": 1,
      "total_tax_amount": 10000,
      "total_amount": 50000
    },
    {
      "reference": "Giftcard zhurkS2IXZ",
      "name": "Discounts",
      "type": "gift_card",
      "tax_rate": 2500,
      "unit_price": 0,
      "quantity": 1,
      "total_discount_amount": 406250,
      "total_tax_amount": 0,
      "total_amount": -406250
    }
  ],
  "order_amount": 0,
  "order_tax_amount": 81250,
  "billing_address": {
    "given_name": "Jonas",
    "family_name": "XXXX",
    "street_address": "XXXX XXX",
    "city": "Blg",
    "country": "SE",
    "postal_code": "79350",
    "email": "Xe"
  }
}

I agree that it look confusing, but it seams to work. 

I read in Klarna Docs https://docs.klarna.com/klarna-payments/in-depth-knowledge/discounts/#gift-cards
that for Gift cards you should set the TotalTaxAmount to Zero. The order_tax_amount adds up correctly possibly Klarna only checks on that.

**Comment by mattbrailsford** [comment]
Hmmmm, that is super weird. Can you test the case I presented? specifically when the GC is ever so slightly less than the total order amount? I would expect that to fail, but if Klarana is happy with the math, maybe we can add this in.

**Comment by jonas-jaderberg** [comment]
Yes, almost same values

Order Total Price inc Tax = 95
Order Tax Amount = 19

A gift card of 90
I pay 5 perfectly fine in Klarna, the tax is 19.

Here is the log

{
  "merchant_urls": {},
  "merchant_reference1": "ORDER-01471-57563-PBY46",
  "purchase_country": "SE",
  "purchase_currency": "SEK",
  "locale": "sv-SE",
  "order_lines": [
    {
      "reference": "bAtt0.05",
      "name": "BXX 50ml",
      "tax_rate": 2500,
      "unit_price": 9500,
      "quantity": 1,
      "total_tax_amount": 1900,
      "total_amount": 9500
    },
    {
      "reference": "Giftcard OSaXnF4n1K",
      "name": "Discounts",
      "type": "gift_card",
      "tax_rate": 2500,
      "unit_price": 0,
      "quantity": 1,
      "total_discount_amount": 9000,
      "total_tax_amount": 0,
      "total_amount": -9000
    }
  ],
  "order_amount": 500,
  "order_tax_amount": 1900,
  "billing_address": {
    ...
  }
}

**Comment by mattbrailsford** [comment]
Wow, but hey, if it works it works. Would you be up for submitting a PR of your changes at all?

**Comment by jonas-jaderberg** [comment]
Yes, I can try to do that, probably tomorrow.

**Comment by mattbrailsford** [comment]
That would be awesome. Thank you 🙏

**Comment by mattbrailsford** [comment]
Fixed in 10.0.1, 12.0.1 and 13.0.1
